export const companiesNames = [
  {
    id: 1,
    pathName: 'tata-consultancy-services',
    name: "Tata Consultancy Services",
    logo: "/image/company-logos/TCS-Logo.png",
  },
  {
    id: 2,
    pathName: 'infosys',
    name: "Infosys",
    logo: "/image/company-logos/Infosys_logo.png",
  },
  {
    id: 3,
    pathName: 'wipro',
    name: "Wipro",
    logo: "/image/company-logos/Wipro-logo.png",
  },
  {
    id: 4,
    pathName: 'hcl-technologies',
    name: "HCL Technologies",
    logo: "/image/company-logos/HCL-Logo.png",
  },
  {
    id: 5,
    pathName: 'tech-mahindra',
    name: "Tech Mahindra",
    logo: "/image/company-logos/Tech_Mahindra_New_Logo.png",
  },
  {
    id: 6,
    pathName: 'larsen-toubro-infotech',
    name: "Larsen & Toubro Infotech",
    logo: "/image/company-logos/LandT_Infotech.png",
  },
  {
    id: 7,
    pathName: 'mindtree',
    name: "Mindtree",
    logo: "/image/company-logos/Mind-Tree-Logo.png",
  },
  {
    id: 8,
    pathName: 'mphasis',
    name: "Mphasis",
    logo: "/image/company-logos/Mphasis-logo.png",
  },
  {
    id: 9,
    pathName: 'persistent-systems',
    name: "Persistent Systems",
    logo: "/image/company-logos/Persistent-logo.png",
  },
  {
    id: 10,
    pathName: 'hexaware-technologies',
    name: "Hexaware Technologies",
    logo: "/image/company-logos/HexAware-logo.png",
  },
  {
    id: 11,
    pathName: 'zensar-technologies',
    name: "Zensar Technologies",
    logo: "/image/company-logos/ZenSar-logo.png",
  },
  {
    id: 12,
    pathName: 'cyient',
    name: "Cyient",
    logo: "/image/company-logos/Cyient-logo.png",
  },
  {
    id: 13,
    pathName: 'niit-technologies',
    name: "NIIT Technologies",
    logo: "/image/company-logos/NIIT_Technologies_Logo.png",
  },
  {
    id: 14,
    pathName: 'oracle-financial-services-software',
    name: "Oracle Financial Services Software",
    logo: "/image/company-logos/Oracle_logo.png",
  },
  {
    id: 15,
    pathName: 'kpit-technologies',
    name: "KPIT Technologies",
    logo: "/image/company-logos/KPIT-TECH-logo.png",
  },
  {
    id: 16,
    pathName: 'lt-technology-services',
    name: "L&T Technology Services",
    logo: "/image/company-logos/L&T-Logo.png",
  },
  {
    id: 17,
    pathName: 'mastek',
    name: "Mastek",
    logo: "/image/company-logos/Mastak-logo.png",
  },
  {
    id: 18,
    pathName: 'mindfire-solutions',
    name: "Mindfire Solutions",
    logo: "/image/company-logos/Mindfire-logo.png",
  },
  {
    id: 19,
    pathName: 'polaris-consulting-services',
    name: "Polaris Consulting & Services",
    logo: "/image/company-logos/Polaris-logo.png",
  },
  {
    id: 20,
    pathName: 'quest-global',
    name: "QuEST Global",
    logo: "/image/company-logos/Quest-logo.png",
  },
];
